services:
  - type: web
    name: ai-prompt-generator
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    envVars:
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
